// Profile content is separate from the project catalogue.
const CONTENT = {
  email:'jarrett.chen217@gmail.com', github:'https://github.com/JarrettChen217', linkedin:'https://www.linkedin.com/in/chen-hao-j33625/', instagram:'https://www.instagram.com/jarrettchen7/', instagramHandle:'@jarrettchen7', wechat:'Che8147',
  internships:[
    {id:'cummins-us',region:'us',roleKey:'data-analytics',company:['Cummins Inc. — Turbo Technologies','康明斯公司 — 涡轮增压技术'],place:['Charleston, SC, United States','美国南卡罗来纳州查尔斯顿'],role:['Data Analytics Intern','数据分析实习生'],date:['May 2026 – Sep 2026','2026年5月 – 2026年9月'],excerpt:['Data and AI-agent workflows for manufacturing analysis, combining reproducible rotor-balancing studies, safe read-only tools, and data and BI pipelines.','围绕制造测试分析开发数据与 AI Agent 工作流，涵盖可复现的转子动平衡研究、安全只读工具，以及数据与 BI 管道。'],tech:'Python · Signal processing · AI agents · BI',summary:['I developed data and AI-agent workflows for manufacturing analysis, including reproducible rotor-balancing studies, approval-gated read-only tools, and data and BI pipelines. The internship combined Python, signal processing, safe agent operations, and collaboration with engineering teams across the United States, China, and the United Kingdom.','我围绕制造测试分析开发数据与 AI Agent 工作流，包括可复现的转子动平衡研究、带审批门控的只读工具，以及数据与 BI 管道。这段经历结合了 Python、信号处理、Agent 安全机制，以及与美国、中国和英国工程团队的协作。'],highlights:[['Investigated a correction-angle mismatch between manufacturing systems and built a reproducible validation workflow.','研究制造系统间的修正角差异，并建立可复现的验证流程。'],['Built approval-gated, refuse-by-default data tools that remained read-only against production sources.','构建带审批门控、默认拒绝且对生产数据源保持只读的数据工具。'],['Collaborated across sites and participated in a Cummins-organized Charleston coastal cleanup.','参与跨地区工程协作，并参加由 Cummins 组织的查尔斯顿海岸清洁志愿活动。']],gallery:[
      {src:'assets/internships/cummins-us-featured-1600.webp',thumbnail:'assets/internships/cummins-us-featured-800.webp',width:1600,height:1208,thumbnailWidth:800,alt:['Hao Chen standing beside a Cummins sign in Charleston','Hao Chen 在查尔斯顿的 Cummins 标识旁'],caption:['Charleston internship, outside a Cummins sign.','查尔斯顿实习期间，于 Cummins 标识旁。']},
      {src:'assets/internships/cummins-us-office-1600.webp',thumbnail:'assets/internships/cummins-us-office-800.webp',width:1600,height:1057,thumbnailWidth:800,alt:['Hao Chen with an internship colleague in an office','Hao Chen 与一位实习同事在办公室合影'],caption:['An office moment with an internship colleague.','与一位实习同事的办公室瞬间。']},
      {src:'assets/internships/cummins-us-beach-1600.webp',thumbnail:'assets/internships/cummins-us-beach-800.webp',width:1600,height:1013,thumbnailWidth:800,alt:['Intern cohort gathering at a Charleston beach','实习生同届成员在查尔斯顿海滩聚会'],caption:['Intern cohort beach outing in the Charleston area.','查尔斯顿地区的实习生同届海滩活动。']},
      {src:'assets/internships/cummins-us-boat-1600.webp',thumbnail:'assets/internships/cummins-us-boat-800.webp',width:1600,height:1067,thumbnailWidth:800,alt:['Intern cohort group during a Charleston outing on a boat','实习生同届成员在查尔斯顿乘船活动中合影'],caption:['Intern cohort Charleston outing on a boat.','实习生同届成员在查尔斯顿的乘船活动。']}
    ]},
    {id:'accenture',region:'remote',roleKey:'ai-technology',company:['Accenture Co., Ltd.','埃森哲有限公司'],place:['Remote','远程'],role:['AI Technology Intern','人工智能技术实习生'],date:['Jul 2024 – Aug 2024','2024年7月 – 2024年8月'],excerpt:['Applied machine-learning workflows for review sentiment classification and store-sales forecasting, spanning data preparation, feature engineering, model evaluation, and analysis.','参与评论情感分类与门店销量预测等应用型机器学习工作，覆盖数据预处理、特征工程、模型评估与分析呈现。'],tech:'Python · TF-IDF · XGBoost · LSTM · scikit-learn',summary:['I worked on applied machine-learning workflows for review sentiment classification and store-sales forecasting, contributing data preprocessing, feature engineering, model evaluation, and stakeholder-facing analysis with Python, TF-IDF, XGBoost, LSTM, and scikit-learn.','我参与评论情感分类与门店销量预测等应用型机器学习工作，使用 Python、TF-IDF、XGBoost、LSTM 与 scikit-learn 完成数据预处理、特征工程、模型评估和面向协作方的分析呈现。'],highlights:[]},
    {id:'cummins-china',region:'cn',roleKey:'software-development',company:['Cummins (China) Investment Co., Ltd.','康明斯（中国）投资有限公司'],place:['Beijing, China','中国北京'],role:['Software Development Intern','软件开发实习生'],team:['Digital Team','数字化团队'],date:['Dec 2023 – Jan 2024','2023年12月 – 2024年1月'],excerpt:['Two sprint-based Digital Team projects: Python backend logic for fuel-use comparisons and a PySpark pipeline for cumulative telemetry data.','在数字化团队参与两个迭代项目：开发油耗方案比较的 Python 后端逻辑，以及处理遥测累积量数据的 PySpark 管道。'],tech:'PySpark · Spark SQL · Python · NumPy · Unit testing',summary:['Within Cummins China’s Beijing Digital Team, I contributed to two sprint-based projects. I built and tested Python backend logic for a mining haul-truck decision workflow that compared predicted fuel use across operating scenarios, then developed PySpark transformations for heartbeat telemetry cumulative metrics, feature data, and daily full and incremental tables.','在康明斯中国北京数字化团队实习期间，我参与了两个迭代项目。我首先开发并测试矿用车辆决策流程的 Python 后端逻辑，用于比较不同工况下的预测油耗；随后开发 PySpark 转换流程，处理心跳遥测的累积量指标、特征数据，以及每日全量表与增量表。'],background:['This month-long internship covered two complete sprint cycles inside the Beijing Digital Team. The team translated business-unit needs into data-backed products through a cross-functional chain: product colleagues framed the use case, data operations prepared source data, advanced analytics supplied cleaned data and models, and IT engineers turned those pieces into testable software and data pipelines. My work sat at that final implementation boundary, where model logic, data contracts, validation, and frontend needs had to meet.','这段近一个月的实习覆盖了北京数字化团队的两个完整迭代。团队通过跨职能链路将各业务单元的需求转化为数据产品：产品同事定义使用场景，数据运维准备源数据，高级分析团队提供清洗后的数据与模型，再由 IT 工程团队将其落地为可测试的软件与数据管道。我的工作位于最后的实现边界，需要让模型逻辑、数据契约、输入校验与前端需求真正衔接起来。'],highlights:[
      ['Requirement clarity is part of engineering: ambiguous inputs became explicit ranges, categories, and JSON-ready contracts before implementation.','需求澄清本身就是工程工作：在实现前，将模糊输入整理为明确的范围、类别与可用于 JSON 交互的数据契约。'],
      ['Testing mattered as much as the happy path; mocks and unit tests made backend work verifiable before full frontend integration.','测试与主流程同样重要；通过 mock 与单元测试，在完整前后端联调前验证后端逻辑。'],
      ['A focused Spark ramp-up connected distributed processing concepts to a real daily incremental-and-full-snapshot pipeline.','集中学习 Spark 后，将分布式处理概念应用到真实的每日增量与全量快照管道中。'],
      ['The experience made the full product chain visible, from business need and analytics model to implementation, review, and handover.','这段经历让我看清从业务需求、分析模型，到工程实现、评审与交付的完整产品链路。']
    ],work:[
      {label:['Sprint 153 · Python backend','Sprint 153 · Python 后端'],title:['Mining haul-truck fuel comparison','矿用车辆油耗方案比较'],body:['Built the Python backend workflow for a mining haul-truck decision tool. It accepted operating inputs, evaluated candidate route and vehicle combinations with existing prediction models, and returned comparison data plus the lowest predicted average fuel use for the frontend.','为矿用车辆决策工具开发 Python 后端流程：接收工况输入，调用已有预测模型评估候选路线与车辆组合，并向前端返回比较数据和预测平均油耗最低的方案。'],challenge:['Turn a loosely defined route-and-vehicle question into a stable interface while the frontend and backend were being developed in parallel. The workflow needed to accept practical operating inputs, reuse existing prediction models, and compare candidates consistently.','在前后端并行开发的情况下，将较为模糊的路线与车型选择问题转化为稳定接口。流程需要接收实际工况输入、复用已有预测模型，并以统一方式比较候选方案。'],role:['I owned the IT-side backend logic between user input and model output: data structures, calculations, validation, model calls, aggregation, and the comparison result returned to the frontend.','我负责用户输入与模型输出之间的 IT 后端逻辑，包括数据结构、计算、输入校验、模型调用、结果聚合，以及返回前端的比较结果。'],contributions:[['Mapped slope, elevation, speed, payload, weather, and road-condition inputs into model-ready calculations without exposing the underlying model.','将坡度、高程差、速度、载重、天气与路况等输入转换为模型所需的计算参数，同时不暴露底层模型。'],['Structured route segments and vehicle scenarios as reusable Python objects, then prepared the inputs and outputs for JSON-based integration.','将路线分段与车辆工况封装为可复用的 Python 对象，并为基于 JSON 的前后端集成准备输入输出。'],['Added server-side validation and unit tests for supported operating ranges and output calculations.','为支持的工况范围与输出计算加入后端数据校验和单元测试。']],validation:['Unit tests covered valid and invalid ranges, calculation paths, and model boundaries. Mocked model calls allowed the surrounding backend flow to be checked before integrated testing with the frontend.','单元测试覆盖有效与无效输入范围、计算路径和模型边界；通过 mock 模型调用，在前端联调前验证外围后端流程。'],outcome:['The completed workflow produced comparison rows for the candidate combinations and identified the option with the lowest predicted average fuel use, ready for integrated testing.','完成后的流程能够生成候选组合的比较数据，并选出预测平均油耗最低的方案，进入集成测试阶段。']},
      {label:['Sprint 154 · PySpark data engineering','Sprint 154 · PySpark 数据工程'],title:['Heartbeat cumulative-data pipeline','心跳遥测累积量数据管道'],body:['Developed PySpark transformations for engine heartbeat telemetry, joining tagged events with master data to derive cumulative fuel and operating-time measures and feature records.','开发用于发动机心跳遥测数据的 PySpark 转换流程，将带标签事件与主数据关联，生成燃油与运行时间的累积量指标及特征记录。'],challenge:['Create a repeatable daily transformation from tagged telemetry and master data, then reconcile each day’s result with the previous full snapshot. Production data and cluster access were intentionally restricted, so the logic had to be developed with representative local samples.','基于带标签遥测数据与主数据建立可重复的每日转换流程，再将当天结果与前一日全量快照对齐。由于生产数据与集群访问受到限制，逻辑需要使用具有代表性的本地样本开发。'],role:['After a focused Spark ramp-up, I implemented the PySpark and Spark SQL transformations for measured values, feature records, daily increments, and the rolling full table.','在集中学习 Spark 后，我负责实现 measured value、特征记录、每日增量及滚动全量表所需的 PySpark 与 Spark SQL 转换。'],contributions:[['Calculated first, last, and delta measures per engine while handling missing values and unit conversions.','按发动机计算首值、末值与差值指标，并处理缺失值和单位转换。'],['Joined tagged events with master records to produce the measured and feature datasets required by the next processing layer.','将带标签事件与主数据关联，生成下一处理层所需的 measured 数据与特征数据集。'],['Combined daily incremental results with the prior full snapshot, carrying forward valid cumulative values for engines without new daily events.','将每日增量结果与前一日全量快照合并，并为当日无新事件的发动机沿用有效累积值。']],validation:['I checked schemas, joins, windowed first/last values, missing-data branches, and carry-forward behaviour against local sample data. The local environment could not reproduce production-scale volume, so this case study does not claim cluster deployment or production ownership.','我使用本地样本检查 schema、关联逻辑、窗口首末值、缺失数据分支与累积值沿用行为。由于本地环境无法复现生产规模，本案例不宣称完成了集群部署或拥有生产流程。'],outcome:['The resulting pipeline logic represented both the day’s newly measured records and an updated cumulative full snapshot, while preserving valid history for assets without new events.','最终管道逻辑同时表达当天新增的测量记录与更新后的累积全量快照，并为无新事件的设备保留有效历史。']}
    ],process:{kicker:['Internship process','实习过程'],heading:['Two sprints, one delivery practice','两个迭代，一套交付实践'],intro:['The work progressed from clarifying an uncertain software boundary to implementing and testing a Python service, then repeated the same learning-and-delivery loop in a new distributed-data stack.','工作从澄清不确定的软件边界开始，推进到 Python 服务的实现与测试；随后又在新的分布式数据技术栈中重复了同样的学习与交付循环。'],stages:[
      {id:'clarify-contract',label:['Clarify','澄清'],title:['Turn operating questions into an interface','将工况问题转化为接口'],body:['The first project began with unresolved details around accepted inputs, load states, and how frontend data would enter and leave the backend. I treated those decisions as part of the implementation rather than assumptions hidden in code.','第一个项目开始时，允许的输入、载重状态，以及前端数据如何进入和离开后端仍未完全明确。我把这些决策视为实现的一部分，而不是隐藏在代码里的假设。'],contribution:['Defined class-based scenario structures, documented validation boundaries, and prepared a JSON-ready input/output shape for integration.','定义基于类的工况结构，整理输入校验边界，并为联调准备可用于 JSON 交互的输入输出格式。'],findings:[['Input ranges needed explicit ownership.','输入范围需要明确负责人。'],['Frontend and backend contracts had to evolve together.','前后端契约需要同步演进。'],['Clear failure cases simplified later testing.','明确失败场景能够简化后续测试。']]},
      {id:'build-and-test',label:['Build & test','实现与测试'],title:['Make the backend verifiable before integration','让后端在联调前即可验证'],body:['I connected operating inputs to route calculations and existing prediction functions, aggregated the candidate results, and separated validation from the main execution path. Because neighbouring components were still evolving, mocked dependencies kept tests deterministic.','我将工况输入连接到路线计算与已有预测函数，聚合候选结果，并将输入校验从主执行路径中分离。由于相邻组件仍在演进，mock 依赖让测试结果保持可重复。'],contribution:['Implemented the comparison workflow, added server-side validation, and wrote unit tests for both calculations and rejected inputs.','实现方案比较流程，加入后端输入校验，并为计算结果与非法输入编写单元测试。'],findings:[['Small testable functions reduced integration risk.','小而可测试的函数降低了联调风险。'],['Mocks isolated model dependencies.','Mock 隔离了模型依赖。'],['The output stayed presentation-agnostic for frontend use.','输出保持与表现层解耦，便于前端使用。']]},
      {id:'learn-spark',label:['Learn','学习'],title:['Build a working model of distributed data processing','建立对分布式数据处理的可用认知'],body:['Between sprints, I worked through Spark Core, Spark SQL, the pandas API on Spark, SQL window functions, and the layered data-warehouse model. The goal was not just syntax: it was understanding which abstraction fit each transformation and where the assigned pipeline sat in the wider data flow.','两个迭代之间，我集中学习了 Spark Core、Spark SQL、pandas API on Spark、SQL 窗口函数及分层数据仓库模型。目标不仅是掌握语法，更是理解每类转换适合的抽象，以及所负责管道在完整数据流中的位置。'],contribution:['Mapped the assigned measurement task to DataFrame and SQL operations, then used representative samples to rehearse joins, windows, schemas, and missing-data handling.','将测量任务映射为 DataFrame 与 SQL 操作，并使用代表性样本练习关联、窗口、schema 与缺失数据处理。'],findings:[['DataFrame and SQL operations complemented each other.','DataFrame 与 SQL 操作可以互补。'],['Window functions expressed per-asset first and last values.','窗口函数适合表达设备维度的首末值。'],['Warehouse layers clarified the purpose of each output.','数仓分层明确了每类输出的用途。']]},
      {id:'assemble-snapshot',label:['Deliver','交付'],title:['Assemble daily increments and cumulative history','组合每日增量与累积历史'],body:['The second project joined the day’s tagged events with master data, derived measured and feature records, then reconciled that increment with the prior full snapshot. Assets without a new event still needed valid historical values carried forward.','第二个项目将当天的带标签事件与主数据关联，生成测量及特征记录，再把当天增量与前一日全量快照对齐；对于当天没有新事件的设备，仍需沿用有效历史值。'],contribution:['Implemented the PySpark transformation path and verified its branch behaviour locally with sanitised sample data.','实现 PySpark 转换路径，并使用脱敏样本在本地验证各分支行为。'],findings:[['Incremental and full tables served different consumers.','增量表与全量表服务于不同下游。'],['Carry-forward rules protected valid history.','沿用规则能够保护有效历史。'],['Restricted data access required explicit scope boundaries.','受限数据访问要求明确展示边界。']]}
    ]},delivery:{heading:['How the Digital Team moved work','数字化团队如何推进工作'],intro:['My notes captured a recurring handoff chain. Each function added a different form of clarity before the work became a usable product or pipeline.','我的记录呈现出一条持续重复的交付链路：每个职能都增加一种不同的确定性，最终将需求转化为可用产品或数据管道。'],steps:[
      {title:['Business need','业务需求'],body:['A business unit surfaced an operating or customer problem worth solving.','业务单元提出值得解决的运营或客户问题。']},
      {title:['Product framing','产品定义'],body:['Product colleagues shaped the use case, priorities, stories, and expected user experience.','产品同事定义使用场景、优先级、用户故事与预期体验。']},
      {title:['Data readiness','数据准备'],body:['Data operations acquired source data and assessed its structure and availability.','数据运维获取源数据，并判断其结构与可用性。']},
      {title:['Analytics','分析建模'],body:['Advanced analytics cleaned and labelled data, explored patterns, and supplied model logic.','高级分析团队清洗与标注数据、探索规律，并提供模型逻辑。']},
      {title:['Engineering delivery','工程落地'],body:['IT engineers integrated contracts, models, pipelines, testing, and frontend needs into a deliverable system.','IT 工程团队整合接口契约、模型、数据管道、测试与前端需求，形成可交付系统。']}
    ]},boundary:['This public case study is reconstructed from personal internship notes and local development samples. Proprietary datasets, internal identifiers, model artefacts, exact thresholds, system names, and colleague details are intentionally omitted. It describes my completed implementation and validation work without claiming ownership of production deployment.','本公开案例依据个人实习记录与本地开发样本整理。专有数据集、内部标识、模型文件、精确阈值、系统名称与同事信息均有意省略；页面仅描述我完成的实现与验证工作，不宣称拥有生产部署。'],gallery:[
      {src:'assets/internships/cummins-china-portrait-1600.webp',thumbnail:'assets/internships/cummins-china-portrait-800.webp',width:1024,height:683,thumbnailWidth:800,alt:['Hao Chen at a Cummins office in Beijing','Hao Chen 在北京的 Cummins 办公室'],caption:['A Beijing internship moment at Cummins.','在北京 Cummins 实习期间的瞬间。']},
      {src:'assets/internships/cummins-china-team-1600.webp',thumbnail:'assets/internships/cummins-china-team-800.webp',width:1024,height:768,thumbnailWidth:800,alt:['Cummins China internship team at a completion gathering','Cummins 中国实习团队在结业活动中合影'],caption:['A Cummins China internship team completion moment.','Cummins 中国实习团队的结业瞬间。']}
    ]}
  ],
  selectedInternships:[{id:'cummins-us'},{id:'accenture'},{id:'cummins-china'}],
  selected: PROJECTS.selected,
  projects: PROJECTS.projects
};
