// Profile content is separate from the project catalogue.
const CONTENT = {
  email:'jarrett.chen217@gmail.com', github:'https://github.com/JarrettChen217', linkedin:'https://www.linkedin.com/in/chen-hao-j33625/', instagram:'https://www.instagram.com/jarrettchen7/', instagramHandle:'@jarrettchen7', wechat:'Che8147',
  internships:[
    {id:'cummins-us',region:'us',roleKey:'data-analytics',company:['Cummins Inc. — Turbo Technologies','康明斯公司 — 涡轮增压技术'],place:['Charleston, SC, United States','美国南卡罗来纳州查尔斯顿'],role:['Data Analytics Intern','数据分析实习生'],team:['Manufacturing Engineering & Data Analytics','制造工程与数据分析'],date:['May 2026 – Sep 2026','2026年5月 – 2026年9月'],excerpt:['Evidence-led manufacturing analytics spanning balancing-system validation, reviewable decision tools, and a read-only production-data pipeline for BI.','以证据为导向开展制造数据分析，覆盖动平衡系统验证、可评审决策工具，以及面向 BI 的只读生产数据管道。'],tech:'Python · pandas · scikit-learn · React · Flask · Docker · Parquet · Power BI · Codex · GitHub Copilot · Claude Code',summary:['At Cummins Turbo Technologies in Charleston, I worked across manufacturing engineering, data analytics, and software delivery. I built reproducible studies for a balancing-system discrepancy, translated the analysis into a containerized demonstrator, and developed read-only archive tooling and BI foundations for production-test data. I also used high-intensity vibe coding with Codex, GitHub Copilot, and Claude Code to turn repeated engineering tasks into reusable agent skills and durable scripts, while keeping outputs reviewable through tests and evidence checks.','在康明斯涡轮增压技术查尔斯顿团队实习期间，我的工作横跨制造工程、数据分析与软件交付。我为动平衡系统差异建立可复现研究流程，将分析转化为容器化演示工具，并为生产测试数据开发只读归档工具与 BI 数据基础。我也使用 Codex、GitHub Copilot 与 Claude Code 高强度开展 vibe coding，将重复工程任务沉淀为可复用的 Agent Skills 与持久脚本，同时通过测试和证据检查保持输出可评审。'],background:['The internship began with a practical manufacturing question: two independent measurement chains could observe the same production event yet return different correction guidance. That question expanded into three connected needs—build evidence that engineers could reproduce, make the analysis reviewable without notebook knowledge, and create a trustworthy path from a large test archive to operational reporting. Agent-assisted development became a core delivery method: I used Codex, GitHub Copilot, and Claude Code to explore quickly, then converted successful workflows into versioned skills, persistent scripts, tests, and handoff documentation rather than leaving them as one-off prompts.','这段实习从一个实际制造问题开始：两条独立测量链路观察同一生产事件时，可能给出不同的修正建议。由此延伸出三项相互关联的需求——建立工程师可复现的证据、让不熟悉 notebook 的评审者也能检查分析过程，以及为大规模测试归档建立通往运营报表的可信数据路径。Agent 辅助开发成为核心交付方式：我使用 Codex、GitHub Copilot 与 Claude Code 快速探索，再将有效工作流固化为版本化 Skills、持久脚本、测试与交接文档，而不是停留在一次性提示词。'],highlights:[
      ['Evidence boundaries are part of the result. I separated established observations, directional findings, untested hypotheses, and follow-up tests instead of forcing a single root-cause claim.','证据边界本身就是结果的一部分。我将已确认现象、方向性发现、未经验证的假设与后续测试分开记录，而不是强行给出单一根因。'],
      ['Read-only and fail-closed defaults made production data safer to inspect: provenance, manifests, explicit approvals, and auditable issue states travelled with each derived output.','只读与失败即停止的默认策略让生产数据分析更安全：来源、清单、明确审批与可审计的问题状态会随派生结果一起交付。'],
      ['Vibe coding became an engineering multiplier when successful prompts were hardened into reusable skills and persistent scripts. This removed repeated data-ingestion and checking work for both me and teammates.','当有效提示词被固化为可复用 Skills 与持久脚本后，vibe coding 成为工程效率放大器，减少了我和同事反复进行数据摄取与校对的工作。'],
      ['A useful manufacturing tool must survive handoff. Browser checks, containerization, operating guides, and decision records were treated as deliverables rather than cleanup work.','真正可用的制造工具必须经得起交接。浏览器检查、容器化、操作指南与决策记录都被视为正式交付，而不是收尾工作。'],
      ['Cross-site reviews connected plant context with specialists in manufacturing, signal analysis, quality, and data engineering across three countries.','跨地区评审将工厂现场问题与三个国家的制造、信号分析、质量和数据工程专家连接起来。']
    ],work:[
      {label:['Study 01 · Measurement evidence','研究 01 · 测量证据'],title:['Balancing-system validation workflow','动平衡系统验证流程'],body:['Built a reproducible workflow to explain why two independent manufacturing measurement chains produced different correction angles, while deliberately avoiding the assumption that either chain represented ground truth.','建立可复现流程，用于解释两条独立制造测量链路为何产生不同修正角；同时明确不假设任何一方就是绝对真值。'],challenge:['The two paths used separate acquisition hardware, clocks, processing stages, file formats, and angular conventions. A naïve sample-by-sample comparison could therefore turn alignment error into a false technical conclusion.','两条路径使用独立的采集硬件、时钟、处理阶段、文件格式与角度约定。若直接逐样本比较，可能把对齐误差误判为技术结论。'],role:['I designed the analysis and validation workflow: decoding paired outputs, harmonising coordinate conventions, aligning independent signals, comparing direct and physics-informed prediction paths, and packaging the evidence for engineering review.','我负责设计分析与验证流程：解析配对输出、统一坐标约定、对齐独立信号、比较直接预测与物理约束预测路径，并将证据整理为工程评审材料。'],contributions:[['Mapped coordinate and sign conventions before scoring agreement, then preserved the original and transformed values for auditability.','在评估一致性前先梳理坐标与符号约定，并保留原始值和转换值以便审计。'],['Used time-aware alignment and resampling for independently clocked signals rather than treating row positions as equivalent measurements.','针对独立时钟信号采用基于时间的对齐与重采样，而不是把相同行号当作同一测量时刻。'],['Compared multiple prediction paths with frozen holdouts, signed circular-error metrics, scale-invariance checks, and explicit guardrails.','通过冻结留出集、有符号圆周误差指标、尺度不变性检查与明确守卫条件比较多条预测路径。']],validation:['Reproducible notebooks and provenance records separated established observations from directional evidence. Tests that had not yet been run were labelled as such, and the remaining acquisition-chain question was handed over as two controlled isolation experiments.','可复现 notebook 与来源记录将已确认现象和方向性证据区分开来；尚未执行的测试被明确标注，并将剩余的采集链路问题整理为两个受控隔离实验进行交接。'],outcome:['The study narrowed the discrepancy, exposed transfer and operating-range limits, and produced a reviewable evidence package. It did not claim a hardware root cause or production deployment.','研究缩小了差异范围，揭示了迁移能力与运行区间限制，并形成可评审的证据包；页面不宣称已经确定硬件根因或完成生产部署。']},
      {label:['Study 02 · Reviewable software','研究 02 · 可评审软件'],title:['Decision-support web demonstrator','决策支持 Web 演示工具'],body:['Turned the analytical workflow into a full-stack demonstrator so engineers could compare inputs and prediction paths, inspect curve previews, and review results without stepping through research notebooks.','将分析流程转化为全栈演示工具，使工程师无需逐段阅读研究 notebook，即可比较输入与预测路径、检查曲线预览并评审结果。'],challenge:['The research code was useful to its author but too implicit for broader review. The interface needed safe sample selection, visible intermediate behaviour, reliable status reporting, and protection against stale responses.','研究代码对作者有效，但对更广泛评审而言隐含信息过多。界面需要安全选择样本、展示中间行为、可靠报告状态，并避免过期响应覆盖新结果。'],role:['I developed the frontend and backend flow, connected the validated analysis paths, defined status and error behaviour, and packaged the application for repeatable review on another machine.','我开发前后端流程、接入已验证的分析路径、定义状态与错误行为，并将应用打包，使其能够在其他机器上重复评审。'],contributions:[['Built sample and preset selection, paired-data previews, backend-generated curves, and side-by-side prediction results.','实现样本与预设选择、配对数据预览、后端生成曲线，以及并列预测结果。'],['Separated loading, validation, transport, and calculation errors while preventing a slow earlier request from replacing a newer result.','区分加载、校验、传输与计算错误，并防止较慢的旧请求覆盖较新的结果。'],['Containerized the application with configurable data paths and ports, plus a documented clean-machine startup path.','将应用容器化，支持配置数据路径与端口，并记录干净环境下的启动流程。']],validation:['Unit, integration, browser, health-route, and container checks covered the key paths. The containerized demonstrator was exercised across different processor architectures and on clean-machine browser flows.','通过单元、集成、浏览器、健康检查路由与容器测试覆盖关键路径；容器化演示工具也在不同处理器架构与干净机器浏览器流程中完成检查。'],outcome:['The result was a portable review surface for discussing evidence, assumptions, and input behaviour—not a production control application.','最终交付是一个可移植的评审界面，用于讨论证据、假设与输入行为；它不是生产控制应用。']},
      {label:['Study 03 · Data product','研究 03 · 数据产品'],title:['Read-only production-data and BI pipeline','只读生产数据与 BI 管道'],body:['Designed a read-only path from a deeply nested production-test archive to compact columnar outputs and a BI-ready semantic layer. Reusable agent skills and persistent scripts carried much of the repeatable data-ingestion and verification work.','设计从深层嵌套生产测试归档到紧凑列式输出与 BI 语义层的只读路径；由可复用 Agent Skills 与持久脚本承担大量可重复的数据摄取和校验工作。'],challenge:['The archive was too large and structurally irregular for spreadsheet workflows. Schema variations, repeated sequences, unresolved quality definitions, and network traversal cost all threatened reproducibility and trust.','归档规模与结构复杂度都超出表格工作流的承载范围。Schema 差异、重复序列、尚未统一的质量口径与网络遍历成本都会影响可复现性和可信度。'],role:['I built the extraction and profiling workflow, investigated real archive structure, and turned recurring operations into agent-callable skills. This included a Kappa DAT-reading skill that enabled teammates to inspect that archive through the same guarded workflow.','我构建提取与画像流程、调查真实归档结构，并将重复操作沉淀为 Agent 可调用的 Skills，其中包括帮助同事使用同一受控流程检查归档的 Kappa DAT 文件读取 Skill。'],contributions:[['Implemented discovery, inspection, extraction, and profiling commands that kept source archives read-only and emitted Parquet, manifests, digests, and audit records.','实现发现、检查、提取与画像命令；始终保持源归档只读，并输出 Parquet、清单、摘要与审计记录。'],['Used Codex, GitHub Copilot, and Claude Code to build and iterate on reusable skills, then retained deterministic scripts and tests as the durable execution layer.','使用 Codex、GitHub Copilot 与 Claude Code 构建和迭代可复用 Skills；随后以确定性脚本和测试作为持久执行层。'],['Built the Kappa DAT-reading skill for a teammate, packaging file discovery, parsing, validation, and clear failure states into a repeatable workflow.','为同事构建 Kappa DAT 文件读取 Skill，将文件发现、解析、校验与明确失败状态封装为可重复流程。'],['Profiled schema and duplicate behaviour empirically, then translated unresolved reporting questions into decision records and data guards instead of silently inventing answers.','通过实证方式分析 schema 与重复行为，并将尚未解决的报表问题转化为决策记录与数据守卫，而不是静默猜测。']],validation:['A full-month pilot exercised the archive path at multi-million-row scale. Failure injection checked that incomplete or corrupt work could not publish as a successful result, while manifests and issue codes made flagged outputs diagnosable.','整月试点在千万级记录规模上验证归档路径；故障注入检查确保不完整或损坏的工作不会被当作成功结果发布，清单与问题代码则让异常输出可诊断。'],outcome:['The skills and persistent scripts turned repeated ingestion and cross-checking into reproducible runs, saving substantial engineering and review time. The handoff also included the archive-to-Parquet workflow, operating guides, and explicit unsupported-data boundaries.','Skills 与持久脚本将重复的数据摄取和交叉校对转化为可复现运行，节省了大量工程与审核时间；交接内容还包括归档到 Parquet 的流程、操作指南及明确的不支持数据边界。']}
    ],agentSkills:{kicker:['Agent Skills engineering','Agent Skills 工程化'],heading:['From repeated prompt to shared engineering capability','从重复提示词到共享工程能力'],intro:['High-intensity work with Codex, GitHub Copilot, and Claude Code was useful because successful conversations did not remain chat history. I converted recurring procedures into reviewable Skills, kept deterministic work in scripts and tests, and used GitHub as the versioned validation and distribution path.','与 Codex、GitHub Copilot 和 Claude Code 的高强度协作之所以真正产生价值，是因为有效对话没有停留在聊天记录中。我将重复流程转化为可评审的 Skills，把确定性工作保留在脚本与测试中，并以 GitHub 作为版本化验证和传播路径。'],examples:[
      {title:['Read-only archive access','只读归档访问'],body:['Skills guided safe discovery, inspection, and profiling while persistent commands preserved source immutability, provenance, manifests, and explicit failure states.','Skills 引导安全发现、检查与画像；持久命令则保证源数据不可变，并记录来源、清单与明确失败状态。']},
      {title:['Controlled ingest and pairing','受控摄取与配对'],body:['Repeated ingest, synchronization, and paired-run preparation became named workflows with guarded inputs, reviewable outputs, and less manual cross-checking.','重复的数据摄取、同步与配对准备被整理为具名工作流，包含受控输入、可评审输出，并减少人工交叉校对。']},
      {title:['Kappa DAT reading and export','Kappa DAT 读取与导出'],body:['A teammate-facing Skill packaged file discovery, parsing, validation, preview, explicit confirmation, export, and reporting into one repeatable path.','面向同事的 Skill 将文件发现、解析、校验、预览、明确确认、导出与结果报告封装为一条可重复路径。']},
      {title:['Portable meeting transcription','可移植会议转录'],body:['A tool-neutral Skill kept multilingual transcription instructions beside its scripts and reproducible environment so the same workflow could be used while working with Codex, GitHub Copilot, and Claude Code.','工具中立的 Skill 将多语言转录说明、脚本与可复现环境放在一起，使 Codex、GitHub Copilot 与 Claude Code 的协作都能复用同一套流程。']}
    ],stages:[
      {title:['Extract the operating contract','提取操作契约'],body:['I first turned a successful agent conversation into a concise Skill: when to use it, which evidence to inspect, what must remain read-only, where approval is required, and what a complete report contains.','先把一次成功的 Agent 对话整理为精炼的 Skill：何时使用、检查哪些证据、哪些内容必须只读、何处需要确认，以及完整报告应包含什么。']},
      {title:['Back instructions with durable code','用持久代码支撑说明'],body:['The Skill handled judgement and sequencing; Python and command-line scripts handled parsing, hashing, manifests, exports, and failure checks. Tests hardened the deterministic layer after every agent-assisted iteration.','Skill 负责判断与步骤编排；Python 和命令行脚本负责解析、哈希、清单、导出与失败检查。每次 Agent 辅助迭代后，都由测试加固确定性执行层。']},
      {title:['Make all three coding agents work from the same contract','让三个 Coding Agent 基于同一契约协作'],body:['Installers resolved the repository path and created user-scoped symbolic links for Codex and Claude Code skill directories on macOS and Linux, with directory junctions on Windows. GitHub Copilot used repository instruction and workflow files in VS Code. The installers were idempotent and refused to overwrite real directories; the Kappa editing source and byte-identical mirror were separately verified in fresh Codex and Claude Code sessions.','安装器解析仓库路径，在 macOS 与 Linux 上为 Codex 和 Claude Code 的用户级 Skill 目录创建软链接，在 Windows 上创建目录联接；GitHub Copilot 则在 VS Code 中读取仓库级指令与工作流文件。安装器可重复执行并拒绝覆盖真实目录；Kappa 的主编辑版本与字节级一致镜像另行通过全新 Codex 与 Claude Code 会话验证。']},
      {title:['Validate and propagate through GitHub','通过 GitHub 验证与传播'],body:['Pushes and pull requests triggered GitHub Actions to build the environment, check dependencies, run tests, and verify the mirrored Skill by hash. GitHub provided versioned distribution rather than silent machine deployment: teammates cloned or pulled the repository once linked, so updates became available without copying files again.','推送与拉取请求触发 GitHub Actions 构建环境、检查依赖、运行测试，并通过哈希验证镜像 Skill。GitHub 提供版本化传播，而不是静默部署到个人电脑：同事在完成链接后只需克隆或拉取仓库，更新即可生效，无需再次复制文件。']}
    ]},process:{kicker:['Internship process','实习过程'],heading:['Evidence-led manufacturing analytics','以证据为导向的制造数据分析'],intro:['Across the three workstreams, the same pattern repeated: understand the plant question, protect the source, make transformations observable, test the claims, and leave the next engineer a usable path forward.','三个工作流遵循同一模式：理解工厂问题、保护源数据、让转换过程可观察、验证结论，并为下一位工程师留下可继续推进的路径。'],stages:[
      {id:'frame-question',label:['Frame','定义'],title:['Turn plant observations into testable questions','将现场现象转化为可测试问题'],body:['Stakeholder discussions and production context were translated into explicit comparison targets, reporting definitions, and unresolved decisions. Unknowns stayed visible instead of becoming hidden defaults.','通过协作方讨论与生产现场背景，将问题转化为明确的比较目标、报表定义与待解决决策；未知项保持可见，而不会变成隐藏默认值。'],contribution:['Maintained decision records and separated confirmed facts, assumptions, risks, and follow-up owners.','维护决策记录，并区分已确认事实、假设、风险与后续负责人。'],findings:[['A shared definition comes before a shared dashboard.','共享报表之前，必须先有共享定义。'],['Open questions need owners and evidence, not guesses.','开放问题需要负责人和证据，而不是猜测。'],['Manufacturing context changes how a metric should be read.','制造现场背景会改变指标的解读方式。']]},
      {id:'protect-source',label:['Protect','保护'],title:['Build a read-only, provenance-rich data foundation','建立只读且来源清晰的数据基础'],body:['Every data path treated the production archive as immutable. Derived files carried enough provenance to explain what was read, transformed, flagged, or withheld.','所有数据路径都将生产归档视为不可变源；派生文件携带足够来源信息，用于说明读取、转换、标记或暂缓了哪些内容。'],contribution:['Built discovery, digest, manifest, and guarded publication steps, then exposed repeatable paths through agent skills backed by persistent scripts.','构建发现、摘要、清单与受控发布步骤，再通过由持久脚本支撑的 Agent Skills 暴露可重复执行路径。'],findings:[['Read-only is a system property, not a promise.','只读是一项系统属性，而不仅是口头承诺。'],['A failed run should not resemble a successful delivery.','失败运行不应伪装成成功交付。'],['Provenance reduces both debugging and review time.','来源记录同时降低调试与评审成本。']]},
      {id:'compare-evidence',label:['Analyse','分析'],title:['Align independent measurements before comparing them','先对齐独立测量，再进行比较'],body:['Coordinate conventions, clocks, sampling grids, and processing boundaries were reconciled before claims were scored. Multiple analytical paths were compared without elevating one source into an assumed truth.','在评估结论前，先协调坐标约定、时钟、采样网格与处理边界；同时比较多条分析路径，而不将某一数据源预设为真值。'],contribution:['Created reproducible comparisons, frozen evaluation boundaries, and focused ablations that exposed where evidence transferred and where it did not.','建立可复现比较、冻结评估边界与聚焦消融实验，揭示证据能够迁移和无法迁移的范围。'],findings:[['Row position is not time alignment.','行号一致不代表时间对齐。'],['Transfer limits matter as much as headline accuracy.','迁移边界与表面准确率同样重要。'],['Directional evidence should remain labelled directional.','方向性证据应持续明确标注为方向性。']]},
      {id:'make-reviewable',label:['Review','评审'],title:['Expose assumptions through tools and reports','通过工具与报表呈现假设'],body:['The analysis became a web demonstrator and a BI foundation so reviewers could inspect inputs, compare paths, and trace metric definitions without depending on the author’s local environment.','分析被转化为 Web 演示工具与 BI 数据基础，使评审者无需依赖作者的本地环境，也能检查输入、比较路径并追踪指标定义。'],contribution:['Designed visible states, guarded interactions, semantic definitions, and bilingual review material for technical and business audiences.','为技术与业务受众设计可见状态、受保护交互、语义定义与双语评审材料。'],findings:[['Visible intermediate states make disagreement productive.','可见的中间状态让分歧更具建设性。'],['Operational definitions belong beside the metric.','运营定义应与指标同时呈现。'],['A demonstrator can support review without implying deployment.','演示工具可以支持评审，但不代表已经部署。']]},
      {id:'validate-handoff',label:['Handoff','交接'],title:['Validate the package, then leave explicit next steps','验证交付包，并留下明确下一步'],body:['Automated checks, browser walkthroughs, container runs, failure injection, and operating guides were used to reduce handoff risk. Remaining experiments and deployment decisions stayed documented rather than disappearing at internship close.','通过自动化检查、浏览器走查、容器运行、故障注入与操作指南降低交接风险；剩余实验与部署决策被明确记录，不因实习结束而消失。'],contribution:['Packaged reproducible artefacts, acceptance checks, known gaps, and controlled follow-up experiments for the receiving teams.','为接手团队整理可复现产物、验收检查、已知缺口与受控后续实验。'],findings:[['Clean-machine validation reveals hidden dependencies.','干净环境验证能够暴露隐藏依赖。'],['Known gaps are part of an honest handoff.','已知缺口是诚实交接的一部分。'],['Ownership and control plans matter before rollout.','推广前必须明确负责人和控制计划。']]}
    ]},delivery:{heading:['From plant question to reviewable evidence','从现场问题到可评审证据'],intro:['The work linked discovery, safe data handling, analysis, review surfaces, and handoff. Each stage produced something the next stage could verify rather than only consume.','工作将问题发现、安全数据处理、分析、评审界面与交接串联起来；每一阶段都向下一阶段提供可验证，而不仅是可使用的产物。'],steps:[
      {title:['Plant question','现场问题'],body:['Engineers and stakeholders surfaced an observed discrepancy or reporting need.','工程师与协作方提出现场差异或报表需求。']},
      {title:['Read-only evidence','只读证据'],body:['Source data was inspected without mutation and wrapped with provenance and explicit issue states.','在不修改源数据的前提下进行检查，并附带来源与明确问题状态。']},
      {title:['Reproducible analysis','可复现分析'],body:['Transformations, alignment, metrics, and evaluation boundaries were made repeatable.','让转换、对齐、指标与评估边界能够重复执行。']},
      {title:['Review surface','评审界面'],body:['Web and BI layers exposed inputs, assumptions, intermediate behaviour, and definitions.','通过 Web 与 BI 层呈现输入、假设、中间行为与定义。']},
      {title:['Validated handoff','验证交接'],body:['Checks, guides, known gaps, and next experiments travelled with the deliverable.','测试、指南、已知缺口与后续实验随交付物一起移交。']}
    ]},boundary:['This public case study paraphrases employer-owned work and intentionally omits proprietary data, internal paths, system and vendor names, machine nameplates, equipment or product identifiers, exact plant-performance figures, model artefacts, and colleague details. Findings that remained directional or untested are labelled accordingly. The photos show only approved team, community, and personal internship moments—never production equipment or identification plates.','本公开案例以概括方式描述雇主所有的工作，并有意省略专有数据、内部路径、系统与供应商品牌、机器铭牌、设备或产品标识、精确工厂绩效数字、模型文件与同事信息。仍属于方向性或未经验证的发现均明确标注。照片仅展示获选的团队、社区与个人实习记录，不包含生产设备或识别铭牌。'],gallery:[
      {src:'assets/internships/cummins-us-featured-1600.webp',thumbnail:'assets/internships/cummins-us-featured-800.webp',width:1600,height:1208,thumbnailWidth:800,alt:['Hao Chen standing beside a Cummins sign in Charleston','Hao Chen 在查尔斯顿的 Cummins 标识旁'],caption:['Charleston internship, outside a Cummins sign.','查尔斯顿实习期间，于 Cummins 标识旁。']},
      {src:'assets/internships/cummins-us-office-1600.webp',thumbnail:'assets/internships/cummins-us-office-800.webp',width:1600,height:1057,thumbnailWidth:800,alt:['Hao Chen with an internship colleague in an office','Hao Chen 与一位实习同事在办公室合影'],caption:['An office moment with an internship colleague.','与一位实习同事的办公室瞬间。']},
      {src:'assets/internships/cummins-us-global-manufacturing-1024.webp',thumbnail:'assets/internships/cummins-us-global-manufacturing-800.webp',width:1024,height:768,thumbnailWidth:800,alt:['Hao Chen with Global Manufacturing colleagues in Charleston','Hao Chen 与全球制造团队同事在查尔斯顿合影'],caption:['With colleagues from Global Manufacturing during the Charleston internship.','查尔斯顿实习期间，与全球制造团队同事合影。']},
      {src:'assets/internships/cummins-us-beach-1600.webp',thumbnail:'assets/internships/cummins-us-beach-800.webp',width:1600,height:1013,thumbnailWidth:800,alt:['Intern cohort gathering at a Charleston beach','实习生同届成员在查尔斯顿海滩聚会'],caption:['Intern cohort beach outing in the Charleston area.','查尔斯顿地区的实习生同届海滩活动。']},
      {src:'assets/internships/cummins-us-boat-1600.webp',thumbnail:'assets/internships/cummins-us-boat-800.webp',width:1600,height:1067,thumbnailWidth:800,alt:['Intern cohort group during a Charleston outing on a boat','实习生同届成员在查尔斯顿乘船活动中合影'],caption:['Intern cohort Charleston outing on a boat.','实习生同届成员在查尔斯顿的乘船活动。']},
      {src:'assets/internships/cummins-us-dinner-1600.webp',thumbnail:'assets/internships/cummins-us-dinner-800.webp',width:1600,height:1200,thumbnailWidth:800,alt:['Charleston intern cohort at a group dinner','查尔斯顿实习生同届成员聚餐合影'],caption:['A dinner with the Charleston intern cohort.','与查尔斯顿实习生同届成员聚餐。']}
    ]},
    {id:'accenture',region:'remote',roleKey:'ai-technology',company:['Accenture Co., Ltd.','埃森哲有限公司'],place:['Remote','远程'],role:['AI Technology Intern','人工智能技术实习生'],team:['Remote AI Project Team','线上 AI 项目团队'],date:['Jul 2024 – Aug 2024','2024年7月 – 2024年8月'],excerpt:['Two applied machine-learning studies completed in a remote internship: review sentiment classification and hourly store-sales forecasting, with an emphasis on feature engineering and model comparison.','在线上实习中完成两项应用型机器学习研究：评论情感分类与门店小时级销量预测，重点实践特征工程与模型比较。'],tech:'Python · pandas · scikit-learn · TF-IDF · Word2Vec · XGBoost · Prophet · LSTM · Jupyter',summary:['During a four-week remote internship, I moved from machine-learning foundations into two end-to-end notebook studies. I built a review sentiment classifier, then an hourly store-sales forecasting workflow, documenting how preprocessing choices, feature design, evaluation scope, and mentor feedback changed each result.','在四周线上实习中，我从机器学习基础练习逐步进入两个端到端 Notebook 项目：先完成评论情感分类，再构建门店小时级销量预测流程，并记录数据预处理、特征设计、评估范围与导师反馈如何影响结果。'],background:['The internship followed a weekly remote cycle of goals, independent notebook work, mentor review, and written reflection. After an initial week covering classification, clustering, and regression with scikit-learn datasets, the remaining weeks focused on two consulting-style exercises: define the target, prepare the data, compare model families, and explain what the evidence did and did not support.','实习采用按周推进的线上节奏：明确目标、独立完成 Notebook、接受导师评审，再进行书面复盘。第一周使用 scikit-learn 数据集练习分类、聚类与回归；后三周集中在两个咨询式练习上：定义目标、准备数据、比较模型，并说明证据能够支持什么、不能支持什么。'],highlights:[
      ['Feature engineering changed the sentiment result more than swapping text models alone: adding structured review context raised the saved notebook results from the high-60% range to the mid-80% range.','在情感分类中，相比只更换文本模型，特征工程带来的变化更明显：加入结构化评论信息后，Notebook 中记录的结果由约 60% 后段提升到 80% 中段。'],
      ['A mistaken grouping choice in the sales task caused rework. I learned to confirm the prediction unit, grouping key, and target horizon before building features.','销量任务中一次错误的分组选择造成返工；我由此学会在特征构建前先确认预测单元、分组键与目标时间范围。'],
      ['Evaluation numbers need context. The final hourly sales check contained only one held-out record per store, so it is presented as a notebook comparison rather than a production benchmark.','评估数字必须附带范围说明。销量任务最终仅对每个门店保留一条小时记录，因此这里只把它作为 Notebook 内部比较，而不是生产级基准。'],
      ['Keeping preprocessing, features, models, metrics, and reflections in reproducible notebooks made mentor review and weekly handover more concrete.','将预处理、特征、模型、指标与复盘保存在可复现 Notebook 中，让导师评审与每周交接更具体。']
    ],work:[
      {label:['Week 2 · Classification','第 2 周 · 分类'],title:['Review sentiment classification','评论情感分类'],body:['Built a three-class sentiment workflow for customer reviews, comparing text representations and classifiers before adding structured review attributes as contextual features.','围绕用户评论构建三分类情感分析流程，先比较文本表示与分类器，再加入结构化评论属性作为上下文特征。'],challenge:['The dataset contained review text, star ratings, and service-related attributes, but no ready-to-use sentiment target. The task required a reproducible label definition, careful text preparation, and evaluation that exposed class-level differences instead of relying on one headline score.','数据包含评论文本、星级与服务相关属性，但没有可直接使用的情感标签。任务需要建立可复现的标签定义、完成文本预处理，并通过能呈现各类别差异的评估方式，而不是只依赖单一总分。'],role:['I implemented the complete notebook workflow: data inspection, label construction, text cleaning, vectorization, feature encoding, train-test preparation, model comparison, and evaluation.','我负责完整 Notebook 流程，包括数据检查、标签构建、文本清洗、向量化、特征编码、训练测试准备、模型比较与评估。'],contributions:[['Clustered the star-rating signal into three groups and mapped them to good, neutral, and bad sentiment labels.','将星级信号聚为三组，并映射为正向、中性与负向情感标签。'],['Built TF-IDF and Word2Vec representations, then encoded rating, taste, environment, service, time, and comment-length attributes as additional features.','构建 TF-IDF 与 Word2Vec 表示，并将星级、口味、环境、服务、时间和评论长度等属性编码为附加特征。'],['Compared KNN, XGBoost, logistic regression, and a stacking classifier using held-out reports, confusion matrices, and cross-validation.','使用留出集分类报告、混淆矩阵与交叉验证，比较 KNN、XGBoost、逻辑回归及 Stacking 分类器。']],validation:['The saved notebook recorded both held-out and five-fold cross-validation results. XGBoost with the combined feature set reached 85.8% held-out accuracy and 84.8% mean cross-validation accuracy; logistic regression with the same feature set recorded 85.5% mean cross-validation accuracy.','保存的 Notebook 同时记录留出集与五折交叉验证结果。组合特征的 XGBoost 留出集准确率为 85.8%，平均交叉验证准确率为 84.8%；相同特征下的逻辑回归平均交叉验证准确率为 85.5%。'],outcome:['The comparison showed that review context materially improved this exercise over text-only representations. More importantly, it made feature design and class-level error analysis part of the model-selection decision.','比较结果表明，在这项练习中，评论上下文信息相较纯文本表示带来了明显提升；更重要的是，特征设计与类别级错误分析成为模型选择的一部分。']},
      {label:['Weeks 3–4 · Regression','第 3–4 周 · 回归'],title:['Hourly store-sales forecasting','门店小时级销量预测'],body:['Prepared hourly records for three stores and compared XGBoost, bagged XGBoost, Prophet, and LSTM approaches using lagged sales, order, price, rolling-window, and rank features.','为三个门店准备小时级记录，并基于销量、订单、单价的滞后特征、滑动窗口特征与排名特征，比较 XGBoost、Bagging XGBoost、Prophet 与 LSTM。'],challenge:['Predict the final hourly sales value for each store from the preceding hours while working with a very small grouped sample. An early misunderstanding about the grouping dimension required the data preparation to be rebuilt.','在分组样本很小的情况下，根据前序小时数据预测每个门店最后一个小时的销量。早期对分组维度的理解偏差导致数据准备需要重新构建。'],role:['I reorganized the source data at store-hour level, implemented the temporal feature pipeline, built the model comparisons, and documented the limitations of the final check.','我重新按门店与小时组织源数据，实现时序特征管道，完成多模型比较，并记录最终检查的范围限制。'],contributions:[['Confirmed the store-level prediction unit, grouped records by hour, and separated the final hourly observation of each store for comparison.','确认门店级预测单元，按小时聚合记录，并将每个门店最后一条小时记录留作比较。'],['Created sales rank, one-hour lag, and three-hour rolling mean, standard-deviation, minimum, and maximum features for sales, order count, and average unit price.','为销量、订单数量与平均单价构建销量排名、一小时滞后，以及三小时滑动均值、标准差、最小值与最大值特征。'],['Evaluated direct and bagged XGBoost, store-specific Prophet models with regressors, and an LSTM sequence prototype.','评估直接 XGBoost 与 Bagging XGBoost、带回归变量的门店级 Prophet，以及 LSTM 序列原型。']],validation:['The notebook compared predictions with one final hourly record from each of three stores. Direct XGBoost recorded RMSE 0.173 and MAE 0.163 on those three records, but the sample is too small to support a general accuracy claim.','Notebook 使用三个门店各一条最终小时记录进行预测比较。直接 XGBoost 在这三条记录上的 RMSE 为 0.173、MAE 为 0.163，但样本过小，不能据此主张模型具备普遍准确性。'],outcome:['The exercise produced a working feature-and-model comparison and exposed how strongly the result depended on grouping, feature construction, and evaluation design.','这项练习形成了可运行的特征与模型比较流程，也直观体现了分组方式、特征构建和评估设计对结果的影响。']}
    ],process:{kicker:['Internship process','实习过程'],heading:['From task brief to evidence-backed comparison','从任务说明到证据支持的比较'],intro:['Each week added one layer to the same working method: establish the learning baseline, define the modeling question precisely, build comparable experiments, then use review evidence to revise the next iteration.','每周工作都为同一方法增加一层：先建立学习基础，再准确界定建模问题，构建可比较实验，最后依据评审证据调整下一轮。'],stages:[
      {id:'build-foundations',label:['Foundations','基础'],title:['Rehearse the complete machine-learning loop','练习完整机器学习闭环'],body:['The first week used standard datasets to practise cleaning, scaling, classification, clustering, regression, tuning, and evaluation before moving into the internship datasets.','第一周使用标准数据集练习清洗、标准化、分类、聚类、回归、调参与评估，为后续实习数据任务做准备。'],contribution:['Implemented small scikit-learn notebooks and used the results to identify preprocessing and standardisation gaps.','完成多个 scikit-learn 小型 Notebook，并通过结果识别预处理与标准化方面的不足。'],findings:[['Evaluation begins with the data pipeline, not the estimator.','评估从数据管道开始，而不是从模型开始。'],['Scaling and missing-value handling changed otherwise simple baselines.','标准化与缺失值处理会改变看似简单的基线结果。']]},
      {id:'define-target',label:['Define','定义'],title:['Make the target and grouping unit explicit','明确目标与分组单元'],body:['The sentiment task needed a defensible label-building method, while the sales task needed the store-hour prediction unit and horizon agreed before aggregation. These decisions determined every later feature and metric.','情感任务需要可说明的标签构建方法；销量任务则需要在聚合前明确门店小时级预测单元与时间范围。这些决定会影响后续所有特征与指标。'],contribution:['Converted ratings into three sentiment groups and, after review, rebuilt the sales preparation around the correct store-hour grouping.','将星级转换为三个情感组，并在评审后按正确的门店小时维度重建销量数据准备。'],findings:[['Labels and groups are modeling assumptions that must be documented.','标签与分组都是必须记录的建模假设。'],['Early clarification prevents expensive downstream rework.','提前澄清能够避免后续高成本返工。']]},
      {id:'engineer-compare',label:['Experiment','实验'],title:['Keep feature sets and model comparisons traceable','保持特征集与模型比较可追踪'],body:['Both studies separated preprocessing, feature construction, model fitting, and evaluation in the notebooks. That made text-only and combined-feature classifiers comparable, and kept temporal features visible across the forecasting models.','两个项目都在 Notebook 中分离预处理、特征构建、模型训练与评估，使纯文本与组合特征分类器可比较，也让不同预测模型使用的时序特征保持可见。'],contribution:['Built reusable feature tables, ran multiple model families, and recorded metrics and confusion matrices beside the code that produced them.','构建可复用特征表，运行多类模型，并将指标与混淆矩阵保存在对应代码旁。'],findings:[['Feature changes needed their own comparison baseline.','特征变化需要独立的比较基线。'],['Class-level metrics revealed errors hidden by overall accuracy.','类别级指标揭示总体准确率掩盖的问题。']]},
      {id:'review-scope',label:['Review','评审'],title:['Use feedback to improve both the model and the claim','用反馈同时改进模型与结论'],body:['Weekly review was not limited to tuning. Mentor feedback prompted new contextual features, corrected grouping logic, and a more careful explanation of what small evaluation samples could support.','每周评审不只关注调参。导师反馈推动了上下文特征的加入、分组逻辑的纠正，以及对小样本评估范围更谨慎的说明。'],contribution:['Revised the notebooks after review and wrote weekly retrospectives that captured the decision, evidence, and next step.','根据评审修改 Notebook，并通过周复盘记录决策、证据与下一步。'],findings:[['A better metric does not remove the need to inspect the test design.','更好的指标不能替代对测试设计的检查。'],['Written reflection turned rework into a reusable practice.','书面复盘把返工转化为可复用的方法。']]}
    ]},delivery:{heading:['Remote delivery rhythm','线上交付节奏'],intro:['The internship used a compact weekly loop that kept remote work visible and reviewable even without an office-based project environment.','实习采用紧凑的周循环，让线上工作即使没有线下项目环境，也能够保持可见与可评审。'],steps:[
      {title:['Weekly objective','每周目标'],body:['A concrete modeling task and expected output defined the week’s scope.','以明确的建模任务与预期产出界定每周范围。']},
      {title:['Notebook implementation','Notebook 实现'],body:['I prepared the data, built features and models, and kept code and results together for review.','我完成数据准备、特征与模型构建，并将代码和结果保存在同一 Notebook 中供评审。']},
      {title:['Mentor review','导师评审'],body:['Results, assumptions, grouping choices, and next experiments were reviewed and corrected.','对结果、假设、分组选择与下一轮实验进行评审和纠正。']},
      {title:['Reflection and handover','复盘与交接'],body:['The weekly summary recorded outcomes, unresolved limits, lessons, and the next objective.','周总结记录产出、尚未解决的限制、收获与下一周目标。']}
    ]},boundary:['This public case study is reconstructed from personal notebooks, weekly summaries, and the final internship report. Raw review text, user identifiers, store identifiers, source datasets, personal documents, and internal details are intentionally omitted. Reported metrics retain the scope of the saved experiments and are not presented as production results.','本公开案例依据个人 Notebook、周总结与实习总结报告整理。原始评论文本、用户标识、门店标识、源数据集、个人文件与内部信息均有意省略；页面所列指标保持原实验范围，不作为生产结果呈现。'],gallery:[
      {src:'assets/internships/accenture-sentiment-labels-1600.webp',thumbnail:'assets/internships/accenture-sentiment-labels-800.webp',width:1600,height:1000,thumbnailWidth:800,alt:['Notebook evidence showing the three-cluster sentiment label construction','Notebook 中展示三类情感标签构建过程的项目证据'],caption:['Building good, neutral, and bad labels from the star-rating signal before text modeling.','在文本建模前，基于星级信号构建正向、中性与负向标签。']},
      {src:'assets/internships/accenture-sentiment-models-1600.webp',thumbnail:'assets/internships/accenture-sentiment-models-800.webp',width:1600,height:1000,thumbnailWidth:800,alt:['Notebook evidence comparing sentiment models and feature sets','Notebook 中比较情感模型与特征集的项目证据'],caption:['Saved classification evidence showing the effect of adding structured review context to text features.','保存的分类实验显示，在文本特征中加入结构化评论信息后的变化。']},
      {src:'assets/internships/accenture-sales-models-1600.webp',thumbnail:'assets/internships/accenture-sales-models-800.webp',width:1600,height:1000,thumbnailWidth:800,alt:['Notebook evidence for hourly store-sales feature engineering and model evaluation','门店小时级销量特征工程与模型评估的 Notebook 项目证据'],caption:['Lagged, rolling-window, and rank features used in the hourly sales comparison.','小时级销量比较中使用的滞后、滑动窗口与排名特征。']}
    ]},
    {id:'cummins-china',region:'cn',roleKey:'software-development',company:['Cummins (China) Investment Co., Ltd.','康明斯（中国）投资有限公司'],place:['Beijing, China','中国北京'],role:['Software Development Intern','软件开发实习生'],team:['Digital Team','数字化团队'],date:['Dec 2023 – Jan 2024','2023年12月 – 2024年1月'],excerpt:['Two sprint-based Digital Team projects: Python backend logic for fuel-use comparisons and a PySpark pipeline for cumulative telemetry data.','在数字化团队参与两个迭代项目：开发油耗方案比较的 Python 后端逻辑，以及处理遥测累积量数据的 PySpark 管道。'],tech:'PySpark · Spark SQL · Python · NumPy · Unit testing',summary:['Within Cummins China’s Beijing Digital Team, I contributed to two sprint-based projects. I built and tested Python backend logic for a mining haul-truck decision workflow that compared predicted fuel use across operating scenarios, then developed PySpark transformations for heartbeat telemetry cumulative metrics, feature data, and daily full and incremental tables.','在康明斯中国北京数字化团队实习期间，我参与了两个迭代项目。我首先开发并测试矿用车辆决策流程的 Python 后端逻辑，用于比较不同工况下的预测油耗；随后开发 PySpark 转换流程，处理心跳遥测的累积量指标、特征数据，以及每日全量表与增量表。'],background:['This month-long internship covered two complete sprint cycles inside the Beijing Digital Team. The team translated business-unit needs into data-backed products through a cross-functional chain: product colleagues framed the use case, data operations prepared source data, advanced analytics supplied cleaned data and models, and IT engineers turned those pieces into testable software and data pipelines. My work sat at that final implementation boundary, where model logic, data contracts, validation, and frontend needs had to meet.','这段近一个月的实习覆盖了北京数字化团队的两个完整迭代。团队通过跨职能链路将各业务单元的需求转化为数据产品：产品同事定义使用场景，数据运维准备源数据，高级分析团队提供清洗后的数据与模型，再由 IT 工程团队将其落地为可测试的软件与数据管道。我的工作位于最后的实现边界，需要让模型逻辑、数据契约、输入校验与前端需求真正衔接起来。'],highlights:[
      ['Requirement clarity is part of engineering: ambiguous inputs became explicit ranges, categories, and JSON-ready contracts before implementation.','需求澄清本身就是工程工作：在实现前，将模糊输入整理为明确的范围、类别与可用于 JSON 交互的数据契约。'],
      ['Testing mattered as much as the happy path; mocks and unit tests made backend work verifiable before full frontend integration.','测试与主流程同样重要；通过 mock 与单元测试，在完整前后端联调前验证后端逻辑。'],
      ['A focused Spark ramp-up connected distributed processing concepts to a real daily incremental-and-full-snapshot pipeline.','集中学习 Spark 后，将分布式处理概念应用到真实的每日增量与全量快照管道中。'],
      ['The experience made the full product chain visible, from business need and analytics model to implementation, review, and handover.','这段经历让我看清从业务需求、分析模型，到工程实现、评审与交付的完整产品链路。']
    ],work:[
      {label:['Sprint 153 · Python backend','Sprint 153 · Python 后端'],title:['Mining haul-truck fuel comparison','矿用车辆油耗方案比较'],body:['Built the Python backend workflow for a mining haul-truck decision tool. It accepted operating inputs, evaluated candidate route and vehicle combinations with existing prediction models, and returned comparison data plus the lowest predicted average fuel use for the frontend.','为矿用车辆决策工具开发 Python 后端流程：接收工况输入，调用已有预测模型评估候选路线与车辆组合，并向前端返回比较数据和预测平均油耗最低的方案。'],challenge:['Turn a loosely defined route-and-vehicle question into a stable interface while the frontend and backend were being developed in parallel. The workflow needed to accept practical operating inputs, reuse existing prediction models, and compare candidates consistently.','在前后端并行开发的情况下，将较为模糊的路线与车型选择问题转化为稳定接口。流程需要接收实际工况输入、复用已有预测模型，并以统一方式比较候选方案。'],role:['I owned the IT-side backend logic between user input and model output: data structures, calculations, validation, model calls, aggregation, and the comparison result returned to the frontend.','我负责用户输入与模型输出之间的 IT 后端逻辑，包括数据结构、计算、输入校验、模型调用、结果聚合，以及返回前端的比较结果。'],contributions:[['Mapped slope, elevation, speed, payload, weather, and road-condition inputs into model-ready calculations without exposing the underlying model.','将坡度、高程差、速度、载重、天气与路况等输入转换为模型所需的计算参数，同时不暴露底层模型。'],['Structured route segments and vehicle scenarios as reusable Python objects, then prepared the inputs and outputs for JSON-based integration.','将路线分段与车辆工况封装为可复用的 Python 对象，并为基于 JSON 的前后端集成准备输入输出。'],['Added server-side validation and unit tests for supported operating ranges and output calculations.','为支持的工况范围与输出计算加入后端数据校验和单元测试。']],validation:['Unit tests covered valid and invalid ranges, calculation paths, and model boundaries. Mocked model calls allowed the surrounding backend flow to be checked before integrated testing with the frontend.','单元测试覆盖有效与无效输入范围、计算路径和模型边界；通过 mock 模型调用，在前端联调前验证外围后端流程。'],outcome:['The completed workflow produced comparison rows for the candidate combinations and identified the option with the lowest predicted average fuel use, ready for integrated testing.','完成后的流程能够生成候选组合的比较数据，并选出预测平均油耗最低的方案，进入集成测试阶段。']},
      {label:['Sprint 154 · PySpark data engineering','Sprint 154 · PySpark 数据工程'],title:['Heartbeat cumulative-data pipeline','心跳遥测累积量数据管道'],body:['Developed PySpark transformations for engine heartbeat telemetry, joining tagged events with master data to derive cumulative fuel and operating-time measures and feature records.','开发用于发动机心跳遥测数据的 PySpark 转换流程，将带标签事件与主数据关联，生成燃油与运行时间的累积量指标及特征记录。'],challenge:['Create a repeatable daily transformation from tagged telemetry and master data, then reconcile each day’s result with the previous full snapshot. Production data and cluster access were intentionally restricted, so the logic had to be developed with representative local samples.','基于带标签遥测数据与主数据建立可重复的每日转换流程，再将当天结果与前一日全量快照对齐。由于生产数据与集群访问受到限制，逻辑需要使用具有代表性的本地样本开发。'],role:['After a focused Spark ramp-up, I implemented the PySpark and Spark SQL transformations for measured values, feature records, daily increments, and the rolling full table.','在集中学习 Spark 后，我负责实现 measured value、特征记录、每日增量及滚动全量表所需的 PySpark 与 Spark SQL 转换。'],contributions:[['Calculated first, last, and delta measures per engine while handling missing values and unit conversions.','按发动机计算首值、末值与差值指标，并处理缺失值和单位转换。'],['Joined tagged events with master records to produce the measured and feature datasets required by the next processing layer.','将带标签事件与主数据关联，生成下一处理层所需的 measured 数据与特征数据集。'],['Combined daily incremental results with the prior full snapshot, carrying forward valid cumulative values for engines without new daily events.','将每日增量结果与前一日全量快照合并，并为当日无新事件的发动机沿用有效累积值。']],validation:['I checked schemas, joins, windowed first/last values, missing-data branches, and carry-forward behaviour against local sample data. The local environment could not reproduce production-scale volume, so this case study does not claim cluster deployment or production ownership.','我使用本地样本检查 schema、关联逻辑、窗口首末值、缺失数据分支与累积值沿用行为。由于本地环境无法复现生产规模，本案例不宣称完成了集群部署或拥有生产流程。'],outcome:['The resulting pipeline logic represented both the day’s newly measured records and an updated cumulative full snapshot, while preserving valid history for assets without new events.','最终管道逻辑同时表达当天新增的测量记录与更新后的累积全量快照，并为无新事件的设备保留有效历史。']}
    ],process:{kicker:['Internship process','实习过程'],heading:['Two sprints, one delivery practice','两个迭代，一套交付实践'],intro:['The work progressed from clarifying an uncertain software boundary to implementing and testing a Python service, then repeated the same learning-and-delivery loop in a new distributed-data stack.','工作从澄清不确定的软件边界开始，推进到 Python 服务的实现与测试；随后又在新的分布式数据技术栈中重复了同样的学习与交付循环。'],stages:[
      {id:'clarify-contract',label:['Clarify','澄清'],title:['Turn operating questions into an interface','将工况问题转化为接口'],body:['The first project began with unresolved details around accepted inputs, load states, and how frontend data would enter and leave the backend. I treated those decisions as part of the implementation rather than assumptions hidden in code.','第一个项目开始时，允许的输入、载重状态，以及前端数据如何进入和离开后端仍未完全明确。我把这些决策视为实现的一部分，而不是隐藏在代码里的假设。'],contribution:['Defined class-based scenario structures, documented validation boundaries, and prepared a JSON-ready input/output shape for integration.','定义基于类的工况结构，整理输入校验边界，并为联调准备可用于 JSON 交互的输入输出格式。'],findings:[['Input ranges needed explicit ownership.','输入范围需要明确负责人。'],['Frontend and backend contracts had to evolve together.','前后端契约需要同步演进。'],['Clear failure cases simplified later testing.','明确失败场景能够简化后续测试。']]},
      {id:'build-and-test',label:['Build & test','实现与测试'],title:['Make the backend verifiable before integration','让后端在联调前即可验证'],body:['I connected operating inputs to route calculations and existing prediction functions, aggregated the candidate results, and separated validation from the main execution path. Because neighbouring components were still evolving, mocked dependencies kept tests deterministic.','我将工况输入连接到路线计算与已有预测函数，聚合候选结果，并将输入校验从主执行路径中分离。由于相邻组件仍在演进，mock 依赖让测试结果保持可重复。'],contribution:['Implemented the comparison workflow, added server-side validation, and wrote unit tests for both calculations and rejected inputs.','实现方案比较流程，加入后端输入校验，并为计算结果与非法输入编写单元测试。'],findings:[['Small testable functions reduced integration risk.','小而可测试的函数降低了联调风险。'],['Mocks isolated model dependencies.','Mock 隔离了模型依赖。'],['The output stayed presentation-agnostic for frontend use.','输出保持与表现层解耦，便于前端使用。']]},
      {id:'learn-spark',label:['Learn','学习'],title:['Build a working model of distributed data processing','建立对分布式数据处理的可用认知'],body:['Between sprints, I worked through Spark Core, Spark SQL, the pandas API on Spark, SQL window functions, and the layered data-warehouse model. The goal was not just syntax: it was understanding which abstraction fit each transformation and where the assigned pipeline sat in the wider data flow.','两个迭代之间，我集中学习了 Spark Core、Spark SQL、pandas API on Spark、SQL 窗口函数及分层数据仓库模型。目标不仅是掌握语法，更是理解每类转换适合的抽象，以及所负责管道在完整数据流中的位置。'],contribution:['Mapped the assigned measurement task to DataFrame and SQL operations, then used representative samples to rehearse joins, windows, schemas, and missing-data handling.','将测量任务映射为 DataFrame 与 SQL 操作，并使用代表性样本练习关联、窗口、schema 与缺失数据处理。'],findings:[['DataFrame and SQL operations complemented each other.','DataFrame 与 SQL 操作可以互补。'],['Window functions expressed per-asset first and last values.','窗口函数适合表达设备维度的首末值。'],['Warehouse layers clarified the purpose of each output.','数仓分层明确了每类输出的用途。']]},
      {id:'assemble-snapshot',label:['Deliver','交付'],title:['Assemble daily increments and cumulative history','组合每日增量与累积历史'],body:['The second project joined the day’s tagged events with master data, derived measured and feature records, then reconciled that increment with the prior full snapshot. Assets without a new event still needed valid historical values carried forward.','第二个项目将当天的带标签事件与主数据关联，生成测量及特征记录，再把当天增量与前一日全量快照对齐；对于当天没有新事件的设备，仍需沿用有效历史值。'],contribution:['Implemented the PySpark transformation path and verified its branch behaviour locally with sanitised sample data.','实现 PySpark 转换路径，并使用脱敏样本在本地验证各分支行为。'],findings:[['Incremental and full tables served different consumers.','增量表与全量表服务于不同下游。'],['Carry-forward rules protected valid history.','沿用规则能够保护有效历史。'],['Restricted data access required explicit scope boundaries.','受限数据访问要求明确展示边界。']]}
    ]},delivery:{heading:['How the Digital Team moved work','数字化团队如何推进工作'],intro:['My notes captured a recurring handoff chain. Each function added a different form of clarity before the work became a usable product or pipeline.','我的记录呈现出一条持续重复的交付链路：每个职能都增加一种不同的确定性，最终将需求转化为可用产品或数据管道。'],steps:[
      {title:['Business need','业务需求'],body:['A business unit surfaced an operating or customer problem worth solving.','业务单元提出值得解决的运营或客户问题。']},
      {title:['Product framing','产品定义'],body:['Product colleagues shaped the use case, priorities, stories, and expected user experience.','产品同事定义使用场景、优先级、用户故事与预期体验。']},
      {title:['Data readiness','数据准备'],body:['Data operations acquired source data and assessed its structure and availability.','数据运维获取源数据，并判断其结构与可用性。']},
      {title:['Analytics','分析建模'],body:['Advanced analytics cleaned and labelled data, explored patterns, and supplied model logic.','高级分析团队清洗与标注数据、探索规律，并提供模型逻辑。']},
      {title:['Engineering delivery','工程落地'],body:['IT engineers integrated contracts, models, pipelines, testing, and frontend needs into a deliverable system.','IT 工程团队整合接口契约、模型、数据管道、测试与前端需求，形成可交付系统。']}
    ]},boundary:['This public case study is reconstructed from personal internship notes and local development samples. Proprietary datasets, internal identifiers, model artefacts, exact thresholds, system names, and colleague details are intentionally omitted. It describes my completed implementation and validation work without claiming ownership of production deployment.','本公开案例依据个人实习记录与本地开发样本整理。专有数据集、内部标识、模型文件、精确阈值、系统名称与同事信息均有意省略；页面仅描述我完成的实现与验证工作，不宣称拥有生产部署。'],gallery:[
      {src:'assets/internships/cummins-china-portrait-1600.webp',thumbnail:'assets/internships/cummins-china-portrait-800.webp',width:1024,height:683,thumbnailWidth:800,alt:['Hao Chen at a Cummins office in Beijing','Hao Chen 在北京的 Cummins 办公室'],caption:['A Beijing internship moment at Cummins.','在北京 Cummins 实习期间的瞬间。']},
      {src:'assets/internships/cummins-china-team-1600.webp',thumbnail:'assets/internships/cummins-china-team-800.webp',width:1024,height:768,thumbnailWidth:800,alt:['Cummins China internship team at a completion gathering','Cummins 中国实习团队在结业活动中合影'],caption:['A Cummins China internship team completion moment.','Cummins 中国实习团队的结业瞬间。']}
    ]}
  ],
  selectedInternships:[{id:'cummins-us'},{id:'accenture'},{id:'cummins-china'}],
  selected: PROJECTS.selected,
  projects: PROJECTS.projects
};

// Company marks are optional. An internship without a matching entry keeps the
// original text-only layout and does not reserve any visual space.
const INTERNSHIP_LOGOS = Object.freeze({
  'cummins-us':{src:'assets/brands/cummins-mark.svg',width:114,height:100,alt:['Cummins logo','康明斯标志']},
  accenture:{src:'assets/brands/accenture-mark.svg',width:32,height:32,alt:['Accenture logo','埃森哲标志']},
  'cummins-china':{src:'assets/brands/cummins-mark.svg',width:114,height:100,alt:['Cummins logo','康明斯标志']}
});
CONTENT.internships.forEach(internship=>{if(INTERNSHIP_LOGOS[internship.id])internship.logo=INTERNSHIP_LOGOS[internship.id];});
